"""empty message

Revision ID: bc0dcd16bf48
Revises: 848ef4e91395
Create Date: 2023-02-17 01:56:47.147481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0dcd16bf48'
down_revision = '848ef4e91395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('items',
    sa.Column('item_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('item_no')
    )
    op.create_table('bills',
    sa.Column('bill_no', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('bill_no')
    )
    op.create_table('orders',
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('no_of_items', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_no')
    )
    op.create_table('orders_items',
    sa.Column('order_no', sa.Integer(), nullable=True),
    sa.Column('item_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_no'], ['items.item_no'], ),
    sa.ForeignKeyConstraint(['order_no'], ['orders.order_no'], )
    )
    op.create_foreign_key(None, 'cashiers', 'bills', ['bill_no'], ['bill_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cashiers', type_='foreignkey')
    op.drop_table('orders_items')
    op.drop_table('orders')
    op.drop_table('bills')
    op.drop_table('items')
    op.drop_table('customers')
    # ### end Alembic commands ###
