"""empty message

Revision ID: bec8b86d7df8
Revises: bc0dcd16bf48
Create Date: 2023-02-27 03:29:11.300648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec8b86d7df8'
down_revision = 'bc0dcd16bf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bills', 'orders', ['order_no'], ['order_no'])
    op.add_column('items', sa.Column('order_no', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('item_no', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'items', ['item_no'], ['item_no'])
    op.alter_column('orders_items', 'item_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders_items', 'order_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders_items', 'order_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders_items', 'item_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'item_no')
    op.drop_column('items', 'order_no')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    # ### end Alembic commands ###
