"""empty message

Revision ID: 848ef4e91395
Revises: 
Create Date: 2023-02-17 01:42:03.223527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848ef4e91395'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashiers',
    sa.Column('cashier_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('cashier_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashiers')
    # ### end Alembic commands ###
